### PR TITLE
Can I use parts of that code in my server soft?

### PR DESCRIPTION
**Pull request by Encritary**
Hi! I see you are updated shoghicp's BigBrother plugin. So, I have a question for you. Can I use parts of your code in my server software(Prismarine, support both mcpe/mcw10e and mcpc): https://github.com/PrismarineMC/Prismarine
And another wuestion. Did you update it? For example, add support for container open/close by client.

### CODE REVIEW

**Comment by va2ron1** [comment]
Right now the plugin only show the other player and his movements, nothing else.

**Comment by Encritary** [comment]
Will you update it?

24 авг. 2016 г. 15:59 пользователь "va2ron1" notifications@github.com
написал:

**Comment by va2ron1** [comment]
Maybe in the future, right now I'm working on other projects.

**Comment by Encritary** [comment]
@va2ron1 can you enter Prismarine Team, for create PC support and other things? I see you have some learned about PC protocol.

**Comment by va2ron1** [comment]
@MrGenga I don't have another way to contact you, so I doing here. I removed pcsupport branch and the repository that I created a few hours ago. I will create a plugin based on BigBrother and for Prismarine. Expect the first review of the plugin in a few hours or in the next days with the changes.

**Pull request closed without merging**
